name: Format JS Code

on: workflow_call

jobs:
    prettier-fixer:
        runs-on: ubuntu-latest

        name: Run Prettier
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Format code with prettier
              run: npm run fmt

            - name: Run build
              run: npm run build

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Format php-and-js code
