name: Format JS Code

on: workflow_call

env:
    PR_NUMBER: '${{ github.event.number }}'
    SOURCE_BRANCH: '$GITHUB_HEAD_REF'
    FIXER_BRANCH: 'auto-fixed/$GITHUB_HEAD_REF'
    TITLE: 'Apply Prettier Fixes'
    DESCRIPTION: 'This merge request applies prettier code style fixes from an analysis carried out through GitHub Actions.'

jobs:
    prettier-fixer:
        if: github.event_name == 'pull_request' && ! startsWith(github.ref, 'refs/heads/auto-fixed/')
        runs-on: ubuntu-latest

        name: Run Prettier
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Prepare Git User
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git checkout -B "${{ env.FIXER_BRANCH }}"

            - name: Format code with prettier
              run: npm run fmt

            - name: Run build
              run: npm run build

            - name: Create Fixer PR
              run: |
                  if [[ -z $(git status --porcelain) ]]; then
                   echo "Nothing to fix.. Exiting."
                   exit 0
                  fi
                  OPEN_PRS=`curl --silent -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=open"`
                  OPEN_FIXER_PRS=`echo ${OPEN_PRS} | grep -o "\"ref\": \"${{ env.FIXER_BRANCH }}\"" | wc -l`
                  git commit -am "${{ env.TITLE }}"
                  git push origin "${{ env.FIXER_BRANCH }}" --force
                  if [ ${OPEN_FIXER_PRS} -eq "0" ]; then
                   curl -X POST \
                   -H "Accept: application/vnd.github.v3+json" \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls" \
                      -d "{ \"head\":\"${{ env.FIXER_BRANCH }}\", \"base\":\"${{ env.SOURCE_BRANCH }}\", \"title\":\"${{ env.TITLE }}\", \"body\":\"${{ env.DESCRIPTION }}\n\nTriggered by #${{ env.PR_NUMBER }}\" }"
                  fi
                  exit 1
